### ISSUE TITLE
using undocumented functions is confusing

### ISSUE THREAD

**Issue by oriSomething** [ParsePlatform/CloudCodeWebhooks-Express#1]
i saw [this line](https://github.com/ParsePlatform/CloudCodeWebhooks-Express/blob/master/server.js#L31):

``` javascript
  parseObject._finishFetch(object);
```

and i couldn't found the function `_finishFetch` in the [docs](http://parse.com/docs/js/api/symbols/Parse.Object.html)

**Comment by gfosco** [comment]
True, since it's an internal method... We don't currently have a public method for setting the 'remote' data for an object from JSON, so that's the best I could do to inflate a real Parse.Object from the POST.  Hopefully in the future we can add more public methods for this type of functionality.
